apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-helm.fullname" . }}
  labels:
    {{- include "dev-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "dev-helm.selectorLabels" . | nindent 4 }}
